# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shiyun Zou
email: shiyun_zou@brown.edu
description: > # this means to ignore newlines until "baseurl:"
  A personal website for machine learning projects and blogs. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://irenesz.github.io/" # the base hostname & protocol for your site
github_username:  irenesz

# Build settings
markdown: kramdown
